"""handle search query drop

Revision ID: 1561695e4217
Revises: 374801b6ad33
Create Date: 2026-02-02 14:38:43.331715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1561695e4217'
down_revision: Union[str, Sequence[str], None] = '374801b6ad33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_chat_sessions_search_query_id_search_queries'), 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_chat_sessions_search_query_id_search_queries'), 'chat_sessions', 'search_queries', ['search_query_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_vacancies_search_query_id_search_queries'), 'vacancies', type_='foreignkey')
    op.create_foreign_key(op.f('fk_vacancies_search_query_id_search_queries'), 'vacancies', 'search_queries', ['search_query_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_vacancy_interview_scores_search_query_id_search_queries'), 'vacancy_interview_scores', type_='foreignkey')
    op.create_foreign_key(op.f('fk_vacancy_interview_scores_search_query_id_search_queries'), 'vacancy_interview_scores', 'search_queries', ['search_query_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_vacancy_interview_scores_search_query_id_search_queries'), 'vacancy_interview_scores', type_='foreignkey')
    op.create_foreign_key(op.f('fk_vacancy_interview_scores_search_query_id_search_queries'), 'vacancy_interview_scores', 'search_queries', ['search_query_id'], ['id'])
    op.drop_constraint(op.f('fk_vacancies_search_query_id_search_queries'), 'vacancies', type_='foreignkey')
    op.create_foreign_key(op.f('fk_vacancies_search_query_id_search_queries'), 'vacancies', 'search_queries', ['search_query_id'], ['id'])
    op.drop_constraint(op.f('fk_chat_sessions_search_query_id_search_queries'), 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_chat_sessions_search_query_id_search_queries'), 'chat_sessions', 'search_queries', ['search_query_id'], ['id'])
    # ### end Alembic commands ###
