"""add_chat_session_search_query

Revision ID: 8afac31e6144
Revises: ab52f47ba538
Create Date: 2026-01-27 18:53:37.047254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8afac31e6144'
down_revision: Union[str, Sequence[str], None] = 'ab52f47ba538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.add_column('chat_sessions', sa.Column('search_query_id', sa.Integer(), nullable=False))
        op.create_foreign_key(op.f('fk_chat_sessions_search_query_id_search_queries'), 'chat_sessions', 'search_queries', ['search_query_id'], ['id'])
    except Exception:
        raise RuntimeError("Error adding search_query_id column. Ensure the chat_sessions table is empty and run the migration again.")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_chat_sessions_search_query_id_search_queries'), 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'search_query_id')
    # ### end Alembic commands ###
