"""Add unified_requirements table

Revision ID: b0125396a4ec
Revises: 11c126e500cd
Create Date: 2026-02-05 15:20:44.433676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0125396a4ec'
down_revision: Union[str, Sequence[str], None] = '11c126e500cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unified_requirements',
    sa.Column('search_query_id', sa.Integer(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['search_query_id'], ['search_queries.id'], name=op.f('fk_unified_requirements_search_query_id_search_queries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unified_requirements'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unified_requirements')
    # ### end Alembic commands ###
