"""initiate_tables

Revision ID: f7e2ec46437e
Revises: 
Create Date: 2026-01-23 23:29:16.701593

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7e2ec46437e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'chat_sessions',
        sa.Column('session_id', sa.String(length=100), nullable=False),
        sa.Column('title', sa.Text(), nullable=True),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('interview_finished', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions')),
        sa.UniqueConstraint('session_id', name=op.f('uq_chat_sessions_session_id')),
    )
    op.create_table(
        'search_queries',
        sa.Column('query', sa.String(), nullable=False),
        sa.Column('total_results', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_search_queries')),
    )
    op.create_table(
        'chat_messages',
        sa.Column('session_id', sa.String(length=100), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.CheckConstraint("role IN ('user', 'tool', 'assistant')", name=op.f('ck_chat_messages_check_role')),
        sa.ForeignKeyConstraint(
            ['session_id'],
            ['chat_sessions.session_id'],
            name=op.f('fk_chat_messages_session_id_chat_sessions'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages')),
    )
    op.create_index('idx_chat_messages_created_at', 'chat_messages', ['created_at'], unique=False)
    op.create_index('idx_chat_messages_session_id', 'chat_messages', ['session_id'], unique=False)
    op.create_table(
        'vacancies',
        sa.Column('search_query_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.Text(), nullable=True),
        sa.Column('company', sa.Text(), nullable=True),
        sa.Column('location', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('url', sa.Text(), nullable=False),
        sa.Column('scrapped', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['search_query_id'], ['search_queries.id'], name=op.f('fk_vacancies_search_query_id_search_queries')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_vacancies')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancies')
    op.drop_index('idx_chat_messages_session_id', table_name='chat_messages')
    op.drop_index('idx_chat_messages_created_at', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('search_queries')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
