"""add_processed_description

Revision ID: ab52f47ba538
Revises: f7e2ec46437e
Create Date: 2026-01-27 17:23:43.854719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab52f47ba538'
down_revision: Union[str, Sequence[str], None] = 'f7e2ec46437e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('processed_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'processed_description')
    # ### end Alembic commands ###
